### PR TITLE
chore: some quality of life fixes

### PR DESCRIPTION
**Pull request by virtuoushub**
#### Context:

Was using https://github.com/excaliburjs/template-ts-vite and noticed that `npm run test` was failing in my environment.

This led me down a bit of a rabbit hole to look into the `@excaliburjs/testing` code, which ultimately had me creating this PR.

---

### changes

- added `devcontainer.json` to aid with development in GitHub Codespaces
- fix up observed bug in `clickPlayButton`
- update dependencies in `package.json`
  - _note:_ due to  https://github.com/cloudhead/node-static/issues/224 switched out use of `node-static` to `@brettz9/node-static`
    - _note: if the changes to use a different package than `node-static` is not what we want here, can look into a different approach._

---

_another note:_ after syncing with @eonarheim [on discord](https://discord.com/channels/1195771303215513671/1271936253012475914/1275460580932718643), seems like using `playwright` similar to [how the `electron template`](https://github.com/excaliburjs/template-electron/blob/main/package.json#L20-L22) is doing testing might be the approach to take for the vite template instead.

---

_note: since the last release was almost 3 years ago, I'm not sure what the future of this package is._

that being said, I think it can benefit from some of these changes.

_Also wondering if a different approach to this change is to update https://github.com/excaliburjs/template-ts-vite/blob/main/package.json#L11 / https://github.com/excaliburjs/template-ts-vite/blob/main/package.json#L35  to use https://github.com/excaliburjs/excalibur-jasmine instead since it was more recently updated._

### CODE REVIEW

**Comment by kamranayub** [comment]
It would be great to have one approach to testing. I think Playwright is a good way forward if we are already using it (I know @eonarheim likes it a lot 😁).

I like the idea of the devcontainer, thanks for that 💯.

**Comment by kamranayub** [comment]
Probably should use Node 22 eh 😅

**Comment by virtuoushub** [comment]
> Probably should use Node 22 eh 😅 (workflow is using node 12)

just pushed a change w/ Node 20 since [it is currently long term service(LTS)](https://nodejs.org/en/about/previous-releases#release-schedule), but happy to bump to 22 too.

**Comment by eonarheim** [comment]
@virtuoushub Thanks for the contribution! I'll 100% accept this.

Agree @kamranayub's, I think Playwright might solve all the problems `excalibur-testing` set out to solve.

**Review by eonarheim — APPROVED** [review]

**Comment by eonarheim** [comment]
@virtuoushub Thanks again for the contribution!

**Comment by eonarheim** [comment]
@virtuoushub Published! 
image

**Comment by virtuoushub** [comment]
> @virtuoushub Thanks again for the contribution!

@eonarheim my pleasure, thanks for the feedback/review/merge!

---

> Agree @kamranayub's, I think Playwright might solve all the problems `excalibur-testing` set out to solve.

I think so too. I am going to _play_ around a little bit more with this approach and see how it goes.

**Pull request merged**
